### ISSUE TITLE
Add mpv as one of the .gif players

### ISSUE THREAD

**Issue by zWolfrost** [SilverEzhik/mpv-msix#11]
It seems that there is no way to add mpv as a gif player. It doesn't show up in the possible players list and if i go to its path (the program files folder) it doesn't open up because i don't have the permission. If there is a way to set it up manually that would also be nice

**Comment by SilverEzhik** [comment]
Since mpv-msix is packaged as an MSIX package, I have to declare the file extensions in the manifest file - this manifest did not include .gif files. I'll go ahead and release a small update which adds gif files to the manifest.

**Comment by SilverEzhik** [comment]
Just pushed out a new update which will allow setting mpv-msix as the default player, it should go live in the store in a day or two.
