### ISSUE TITLE
config-dir= in mpv-launcher.conf

### ISSUE THREAD

**Issue by candrapersada** [SilverEzhik/mpv-msix#12]
can you use `config-dir=` in `mpv-launcher.conf` for example

```
config-dir=D:\mpv\config
single-instance-behavior=replace
sort-file-explorer-selection=yes
raise-existing-window=yes
```

**Comment by SilverEzhik** [comment]
I'm assuming you mean setting where the mpv config is located? There is no key like this supported in mpv-msix, but you can use the `MPV_HOME` environment variable to set the location of the mpv configuration - this is respected both by mpv-msix's `mpv-launcher.conf` and mpv's `mpv.conf`.
