### ISSUE TITLE
Update mpv to v0.36.0

### ISSUE THREAD

**Issue by atilluF** [SilverEzhik/mpv-msix#14]
The new version was released in July. https://github.com/mpv-player/mpv/releases/tag/v0.36.0
Can you submit an update? Thank you

**Comment by SilverEzhik** [comment]
Hi, I've just submitted the 0.36.0 update for certification to the Microsoft Store. I'll let you know once the update is live.

**Comment by atilluF** [comment]
I've just updated the app. Thank you very much 😀
