### ISSUE TITLE
Implement custom mpv.conf option

### ISSUE THREAD

**Issue by artyfox** [SilverEzhik/mpv-msix#4]
Similar to how you can customize the mpv-launcher behaviour by creating "%APPDATA%\mpv\mpv-launcher.conf",

would it be possible to add the ability to create a custom "mpv.conf" in the same location, to adjust the default player settings like the default window location/size and subtitle scaling?

Very neat UWP wrapper, thanks for you work! 🦊

**Comment by SilverEzhik** [comment]
This is already supported by mpv: it will automatically read configuration from `%APPDATA%\mpv\mpv.conf`. You can find more information about configuring mpv itself here: https://mpv.io/manual/

**Comment by artyfox** [comment]
Thanks of the quick follow-up! 

Does this also apply to the [input.conf](https://raw.githubusercontent.com/mpv-player/mpv/master/etc/input.conf) file? If so, would the application look in `%APPDATA%\mpv\input.conf` or `%APPDATA%\mpv\etc\input.conf`?
