### ISSUE TITLE
Instructions on how to use

### ISSUE THREAD

**Issue by miIktoast** [SilverEzhik/mpv-msix#5]
Hi I am what one would call an idiot and do not understand how to use this. I have not been able to find any instructions on how to use/set this up, either that or I am out of my depth. is it only available through win store?

**Comment by SilverEzhik** [comment]
Hi, I'm distributing mpv-msix only through the Microsoft Store. If you just want to install it, that's the best way to do it.

----

The reason for that is that this distribution of mpv relies heavily on the [`msix` app package format](https://docs.microsoft.com/en-us/windows/msix/overview) for its main functionality (file associations and single instance mode). 

However, msix installers *must* be signed to be installed, so my options for distribution are:

1. Distribute through the Microsoft Store - this is what I went with as I already had a developer account
2. Buy an application signing certificate - this is expensive and I'm not sure where to get one
3. Use a self-signed certificate - this will require instructions for trusting my self-signed certificate, which is a pretty dangerous thing to do

If you don't want to install mpv-msix from the Microsoft Store, you can still use mpv by downloading it from https://mpv.io. If you want to make use of mpv-msix's functionality, however, you can build it yourself with a recent version of Visual Studio on Windows 10/11 setup to do Windows SDK/.NET development. I believe it should work as is, the only thing you will need is to provide it valid mpv executable files which you can get from https://mpv.io/installation/. Put all the files that you downloaded in the `mpv\prebuilt\x64` and `mpv\prebuilt\x86` folders - the `mpv` project will copy them in the resulting mpv-msix package.

**Comment by FeyrisTan** [comment]
Is there a way to do this in linux? I tried umpv but thats kinda clunky.

**Comment by SilverEzhik** [comment]
I think umpv is your best bet here - sadly basically nothing this app does will work on Linux.

**Comment by poxu** [comment]
@FeyrisTan    Well, actually, inspired by umpvw I have made a piece of software, which works for linux and windows and does what umpv does

I have named it [runmpv](https://github.com/poxu/runmpv). It is written in Java, but compiles to native code. You still need Windows Redistributables under windows, but as for linux, there's no additional dependencies.

runmpv can work like umpv and open all videos in the same window. Also it can open different mpv windows for files from different directories. I kinda needed that ))

You can take binaries from [runmpv github page](https://github.com/poxu/runmpv/releases). 

 I have tested runmpv on Ubuntu Xfce. I would appreciate if someone tries it on their machine )))
